### ISSUE TITLE
Incorrect dependencies version

### ISSUE THREAD

**Issue by bernier** [benjamind/google-sheets#9]
This module is not working anymore.
Please update it.

I was able to fix the worksheet creation by changing the version of xmlbuilder to 0.4.3. It won't work with the latest version of xmlbuilder (currently 2.2.1)

**Comment by benjamind** [comment]
Oh wow, wasn't even aware anyone was using it!

I'll see if I can find some time in the next couple of weeks, or I'll be happy to merge a pull request if you make one.

**Comment by bernier** [comment]
ok thanks,
this is actually a great module, I'm sure more and more people will use it if you update it :)

**Comment by benjamind** [comment]
Hah....if only I had the time...suffering continual side project overload! :-)

**Comment by benjamind** [comment]
Oh, so it looks like @tedjt already made this fix, I've merged in his branch. Should be working for you now?

**Comment by bernier** [comment]
@benjamind great!
I just found something wrong after updating to version 0.0.5, but not sure about the root of the issue.

I had this message when creating a worksheet:
"POST method does not support concurrency"

I had to remove 'If-Match': '*'
line 125 of lib/worksheet.js

See http://markmail.org/message/mudekfbofojud3yi for more details

**Comment by tedjt** [comment]
fyi I don't know how half baked some of my changes were since I used this in a hackathon project. Glancing at them it seem mostly harmless with some cleanup for changes to the Google Api to get it working. I would note that the addition of the cell api is probably incomplete so you may want to revert 34827fd1447634bd36ecd2b00b5c42b7a5888cfc or at least tag with a comment at the top.

As for if-match. I think needed that header to support cell updates on old sheets that a user currently had open. docs should have more details. https://developers.google.com/gdata/docs/2.0/reference

**Comment by benjamind** [comment]
yeah sorry my bad, I didn't check over that merge at all.....going to quickly run the tests now and fix this up. Thanks!

**Comment by benjamind** [comment]
It looks like row add/delete hasn't worked for some time. Rolled back to earlier versions and its still non functional.

To fix this I'd need to dive into the protocol again, but I've not got the time now, so I've marked the row functionality as unimplemented and pushed this version out to fix the issues from before. I'll try and find some time this week to fix this up if I can.

**Comment by benjamind** [comment]
Ok this is what I get for writing code on my way out the door....

Turns out it was just the test spreadsheet had been broken at some point. Restored it to the proper values and all is now working.

I have left Cells marked as unimplemented till I can get some time to write a few more tests for it and confirm its all good.
